application:
  host: 0.0.0.0

kafka:
  bootstrap_host: kafka0
  bootstrap_port: 9090
  group_id_prefix: prod

grpc:
  app_server_port: 10001

meilisearch:
  host: "meilisearch"
  api_key: "masterkey"
