application:
  port: 4243

object_storage:
  port: 9000
  region: "eu-fr-1"

rabbitmq:
  port: 5672
  content_exchange: "content"
  queue_name_prefix: "fulltext_search_service"

meilisearch:
  port: 7700
  extracted_content_index: "extracted_contents"
