application:
  host: 0.0.0.0

object_storage:
  host: "minio"
  username: "minio"
  password: "password"
  bucket_name: local-bucket

rabbitmq:
  host: "rabbitmq"
  queue_name_prefix: local

meilisearch:
  host: "meilisearch"
  api_key: "masterkey"
