application:
  port: 4242

database:
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "content_ingestion"

object_storage:
  port: 9000
  username: "minio"
  password: "password"
  region: "eu-fr-1"

rabbitmq:
  port: 5672
  content_exchange: "content"

meilisearch:
  port: 7700
  extracted_content_index: extracted_contents
