application:
  host: 0.0.0.0

database:
  host: "postgres"
  require_ssl: false

object_storage:
  host: "minio"
  bucket_name: local-bucket

rabbitmq:
  host: "rabbitmq"
  exchange_name_prefix: local

meilisearch:
  host: "meilisearch"
  api_key: "masterkey"
