application:
  port: 4243

rabbitmq:
  port: 5672
  content_exchange: "content"
  queue_name_prefix: "semantic_search_service"

qdrant:
  rest_port: 6333
  grpc_port: 6334
  collection_vector_size: 384
  collection_distance: "Dot"
